theme: jekyll-theme-cayman
title: Solving Unity Ml Agents with PyTorch
description: In this series of tutroial we're going to solve Unity Enviroment with different algorithms using PyTorch.
plugins:
  - jemoji